# ai-nudge/docker-compose.yml

version: '3.8'

services:
  backend-test: # Service name for the temporary test backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      # --- CHANGE THIS LINE ---
      # OLD: - "8000:8000"
      # NEW: Map host port 8001 to container port 8000
      - "8001:8000" # <--- CHANGED: Host port is now 8001
      
    volumes:
      - .:/app
      
    env_file:
      - ./backend/.env
      
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

    restart: unless-stopped