version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    env_file:
      - ./backend/.env
    networks:
      - ai_nudge_net
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - ai_nudge_net
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000

networks:
  ai_nudge_net:
    driver: bridge
