services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
      - ./backend/.env:/app/.env
    env_file:
      - ./backend/.env
    networks:
      - ai_nudge_net
    # CORRECTED: Changed 'main:app' to 'api.main:app' to point to the correct
    # FastAPI application instance inside the 'api' module.
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    # This command overrides the Dockerfile's `CMD ["npm", "start"]`
    # to run the development server instead.
    command: npm run dev
    depends_on:
      - backend
    networks:
      - ai_nudge_net
    environment:
      # CORRECTED: Point the frontend to the correct internal container name and port.
      - NEXT_PUBLIC_API_URL=http://backend:8000

networks:
  ai_nudge_net:
    driver: bridge