# render.yaml (Only fix Celery paths)

databases:
  - name: ai-nudge-db
    databaseName: ai_nudge_db
    user: ai_nudge_user
    plan: free

services:
  # ---------- BACKEND (FastAPI) ----------
  - type: web
    name: ai-nudge-backend
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /test-db
    plan: starter
    autoDeploy: false
    dockerCommand: "./start_render.sh"
    envVars:
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- CELERY WORKER ----------
  - type: worker
    name: ai-nudge-celery-worker
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    autoDeploy: false
    dockerCommand: "celery -A celery_worker.celery_app worker --loglevel=info --concurrency=2"
    envVars:
      - key: RUNNING_IN_CELERY
        value: "true"
      - key: PYTHONPATH
        value: "/app"
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- CELERY BEAT SCHEDULER ----------
  - type: worker
    name: ai-nudge-celery-beat
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    autoDeploy: false
    dockerCommand: "celery -A celery_worker.celery_app beat --loglevel=info --schedule=/tmp/celerybeat-schedule"
    envVars:
      - key: RUNNING_IN_CELERY
        value: "true"
      - key: PYTHONPATH
        value: "/app"
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- REDIS SERVICE ----------
  - type: keyvalue
    name: ai-nudge-redis
    plan: starter
    ipAllowList: []
