# render.yaml (Backend-Only Version)

databases:
  - name: realestate-db
    databaseName: realestate_db
    user: realestate_user
    plan: free
    postgresMajorVersion: 15

services:
  # ---------- BACKEND (FastAPI) ----------
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /test-db
    plan: starter
    dockerCommand: >
      sh -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: realestate-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- CELERY WORKER ----------
  - type: worker
    name: celery-worker
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    dockerCommand: "celery -A celery_worker.celery_app worker --loglevel=info --concurrency=2"
    envVars:
      - key: RUNNING_IN_CELERY
        value: "true"
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: realestate-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- CELERY BEAT SCHEDULER ----------
  - type: worker
    name: celery-beat
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    dockerCommand: "celery -A celery_worker.celery_app beat --loglevel=info"
    envVars:
      - key: RUNNING_IN_CELERY
        value: "true"
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: realestate-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- REDIS SERVICE ----------
  - type: keyvalue
    name: ai-nudge-redis
    plan: starter
    ipAllowList: []
