# render.yaml (Updated with Auto-Deploy Disabled)

databases:
  - name: ai-nudge-db
    databaseName: ai_nudge_db
    user: ai_nudge_user
    plan: free

services:
  # ---------- BACKEND (FastAPI) ----------
  - type: web
    name: ai-nudge-backend
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /test-db
    plan: starter
    autoDeploy: true  # Add this line
    dockerCommand: >
      sh -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- CELERY WORKER ----------
  - type: worker
    name: ai-nudge-celery-worker
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    autoDeploy: true  # Add this line
    dockerCommand: "celery -A backend.celery_worker.celery_app worker --loglevel=info --concurrency=2"
    envVars:
      - key: RUNNING_IN_CELERY
        value: "true"
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- CELERY BEAT SCHEDULER ----------
  - type: worker
    name: ai-nudge-celery-beat
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    plan: starter
    autoDeploy: true  # Add this line
    dockerCommand: "celery -A backend.celery_worker.celery_app beat --loglevel=info"
    envVars:
      - key: RUNNING_IN_CELERY
        value: "true"
      - fromGroup: ainudge-env-group
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: ai-nudge-redis
          type: keyvalue
          property: connectionString

  # ---------- REDIS SERVICE ----------
  - type: keyvalue
    name: ai-nudge-redis
    plan: starter
    ipAllowList: []
