# render.yaml (Revised)
# NOTE: This blueprint links to the pre-existing 'ainudge-env-group' environment group.

databases:
  - name: realestate-db
    databaseName: realestate_db
    user: postgres
    plan: free
    postgresMajorVersion: 15

redis:
  - name: redis-cache
    plan: free
    ipAllowList: []

services:
  # ---------- BACKEND (FastAPI) ----------
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /test-db
    envVarGroups:
      - ainudge-env-group
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realestate-db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: redis-cache
          property: connectionString
    startCommand: >
      sh -c "alembic upgrade head && uvicorn api.main:app --host 0.0.0.0 --port $PORT"
    plan: starter

  # ---------- FRONTEND (Next.js) ----------
  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./frontend/Dockerfile
    envVarGroups:
      - ainudge-env-group
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: backend
          property: url
      - key: NODE_ENV
        value: production
    startCommand: "npm start"
    plan: starter
    buildFilter:
      paths:
        - "frontend/**"
        - "render.yaml"

  # ---------- CELERY WORKER ----------
  - type: worker
    name: celery-worker
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    envVarGroups:
      - ainudge-env-group
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realestate-db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: redis-cache
          property: connectionString
      - key: RUNNING_IN_CELERY
        value: "true"
    startCommand: "celery -A celery_worker.celery_app worker --loglevel=info --concurrency=2"
    plan: starter

  # ---------- CELERY BEAT SCHEDULER ----------
  - type: worker
    name: celery-beat
    runtime: docker
    repo: https://github.com/vijaypatha/ai-nudge
    dockerfilePath: ./backend/Dockerfile
    envVarGroups:
      - ainudge-env-group
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: realestate-db
          property: connectionString
      - key: REDIS_URL
        fromRedis:
          name: redis-cache
          property: connectionString
      - key: RUNNING_IN_CELERY
        value: "true"
    startCommand: "celery -A celery_worker.celery_app beat --loglevel=info"
    plan: starter