services:
  # Main Backend API Service
  - type: web
    name: ai-nudge-backend
    env: docker
    plan: free
    rootDir: backend
    # buildCommand is removed as it's handled by Dockerfile now
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-nudge-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_DEFAULT_MESSAGING_SERVICE_SID
        sync: false
      - key: TWILIO_VERIFY_SERVICE_SID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_APP_URL
        sync: false # Set this value manually in Render dashboard to your Vercel frontend URL
      - key: GOOGLE_API_KEY # Added from your .env
        sync: false
      - key: GOOGLE_CSE_ID # Added from your .env
        sync: false
      - key: FAQ_AUTO_REPLY_ENABLED # Added from your .env
        sync: false
      - key: MLS_PROVIDER # Added from your .env
        sync: false
      - key: SPARK_API_DEMO_TOKEN # Added from your .env
        sync: false
      - key: RESO_API_BASE_URL # Added from your .env
        sync: false
      - key: RESO_API_TOKEN # Added from your .env
        sync: false
      - key: LLM_PROVIDER # Added from your .env
        sync: false
      - key: SECRET_KEY # Added from your .env
        sync: false


  # Celery Worker Service
  - type: web
    name: ai-nudge-celery-worker
    env: docker
    plan: free
    rootDir: backend
    # buildCommand removed
    startCommand: celery -A celery_worker.celery_app worker --loglevel=info
    envVars:
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-nudge-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_DEFAULT_MESSAGING_SERVICE_SID
        sync: false
      - key: TWILIO_VERIFY_SERVICE_SID
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_APP_URL
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: FAQ_AUTO_REPLY_ENABLED
        sync: false
      - key: MLS_PROVIDER
        sync: false
      - key: SPARK_API_DEMO_TOKEN
        sync: false
      - key: RESO_API_BASE_URL
        sync: false
      - key: RESO_API_TOKEN
        sync: false
      - key: LLM_PROVIDER
        sync: false
      - key: SECRET_KEY
        sync: false


  # Celery Beat Scheduler Service
  - type: web
    name: ai-nudge-celery-beat
    env: docker
    plan: free
    rootDir: backend
    # buildCommand removed
    startCommand: celery -A celery_worker.celery_app beat --loglevel=info
    envVars:
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        fromDatabase:
          name: ai-nudge-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ai-nudge-redis
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_DEFAULT_MESSAGING_SERVICE_SID
        sync: false
      - key: TWILIO_VERIFY_SERVICE_SID
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_APP_URL
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CSE_ID
        sync: false
      - key: FAQ_AUTO_REPLY_ENABLED
        sync: false
      - key: MLS_PROVIDER
        sync: false
      - key: SPARK_API_DEMO_TOKEN
        sync: false
      - key: RESO_API_BASE_URL
        sync: false
      - key: RESO_API_TOKEN
        sync: false
      - key: LLM_PROVIDER
        sync: false
      - key: SECRET_KEY
        sync: false

  # Redis Service
  - type: redis
    name: ai-nudge-redis
    plan: free
    ipAllowList: []

databases:
  # PostgreSQL Database
  - name: ai-nudge-db
    databaseName: ai_nudge_db
    user: ai_nudge_user
    plan: free