"""add_pipeline_run_table

Revision ID: 2ce7c9665fe8
Revises: 357f39f135c0
Create Date: 2025-07-26 20:23:58.732431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce7c9665fe8'
down_revision: Union[str, Sequence[str], None] = '357f39f135c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelinerun',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('events_processed', sa.Integer(), nullable=False),
    sa.Column('campaigns_created', sa.Integer(), nullable=False),
    sa.Column('errors', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelinerun_id'), 'pipelinerun', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipelinerun_id'), table_name='pipelinerun')
    op.drop_table('pipelinerun')
    # ### end Alembic commands ###
