"""Create surveyquestion table and fix portal models

Revision ID: 447f04b9000c
Revises: 8d8a21dcd8ba
Create Date: 2025-08-13 20:41:43.682333

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '447f04b9000c'
down_revision = '8d8a21dcd8ba'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- THIS IS THE FIX: Part 1 ---
    # Manually define the Enum type so we can create it before using it.
    commentertype_enum = sa.Enum('AGENT', 'CLIENT', name='commentertype')
    commentertype_enum.create(op.get_bind())
    
    op.create_table('surveyquestion',
    sa.Column('id', sa.UUID(), nullable=False),  # FIXED: Changed from sqlmodel.sql.sqltypes.GUID()
    sa.Column('user_id', sa.UUID(), nullable=False),  # FIXED: Changed from sqlmodel.sql.sqltypes.GUID()
    sa.Column('survey_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_type', sa.Enum('TEXT', 'TEXTAREA', 'MULTIPLE_CHOICE', 'CHECKBOXES', 'SCALE', name='questiontype'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('placeholder', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('help_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preference_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveyquestion_survey_type'), 'surveyquestion', ['survey_type'], unique=False)
    op.create_index(op.f('ix_surveyquestion_user_id'), 'surveyquestion', ['user_id'], unique=False)
    
    # --- Autogenerated changes for other tables ---
    op.drop_index(op.f('ix_portalfeedback_client_id'), table_name='portalfeedback')
    op.drop_index(op.f('ix_portalfeedback_resource_id'), table_name='portalfeedback')
    op.drop_table('portalfeedback')
    op.drop_index(op.f('ix_portal_client_id'), table_name='portal')
    op.drop_index(op.f('ix_portal_secure_token'), table_name='portal')
    op.drop_index(op.f('ix_portal_user_id'), table_name='portal')
    op.drop_table('portal')
    
    op.add_column('portalcomment', sa.Column('user_id', sa.UUID(), nullable=True))  # FIXED: Changed from sqlmodel.sql.sqltypes.GUID()
    
    # --- THIS IS THE FIX: Part 2 ---
    # Use the predefined enum variable here.
    op.add_column('portalcomment', sa.Column('commenter_type', commentertype_enum, nullable=False))
    
    op.alter_column('portalcomment', 'client_id', existing_type=sa.UUID(), nullable=False)
    op.alter_column('portalcomment', 'resource_id', existing_type=sa.UUID(), nullable=False)
    op.create_index(op.f('ix_portalcomment_user_id'), 'portalcomment', ['user_id'], unique=False)
    op.create_foreign_key(None, 'portalcomment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portalcomment', type_='foreignkey')
    op.drop_index(op.f('ix_portalcomment_user_id'), table_name='portalcomment')
    op.alter_column('portalcomment', 'resource_id', existing_type=sa.UUID(), nullable=True)
    op.alter_column('portalcomment', 'client_id', existing_type=sa.UUID(), nullable=True)
    op.drop_column('portalcomment', 'commenter_type')
    op.drop_column('portalcomment', 'user_id')
    
    op.create_table('portal',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('secure_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='portal_client_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='portal_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='portal_pkey')
    )
    op.create_index(op.f('ix_portal_user_id'), 'portal', ['user_id'], unique=False)
    op.create_index(op.f('ix_portal_secure_token'), 'portal', ['secure_token'], unique=True)
    op.create_index(op.f('ix_portal_client_id'), 'portal', ['client_id'], unique=False)
    op.create_table('portalfeedback',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feedback_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='portalfeedback_client_id_fkey'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], name='portalfeedback_resource_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='portalfeedback_pkey')
    )
    op.create_index(op.f('ix_portalfeedback_resource_id'), 'portalfeedback', ['resource_id'], unique=False)
    op.create_index(op.f('ix_portalfeedback_client_id'), 'portalfeedback', ['client_id'], unique=False)
    op.drop_index(op.f('ix_surveyquestion_user_id'), table_name='surveyquestion')
    op.drop_index(op.f('ix_surveyquestion_survey_type'), table_name='surveyquestion')
    op.drop_table('surveyquestion')
    
    # --- THIS IS THE FIX: Part 3 ---
    # Manually define the Enum type so we can drop it after the column is gone.
    commentertype_enum = sa.Enum('AGENT', 'CLIENT', name='commentertype')
    commentertype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
