"""add_super_user_field

Revision ID: 514e677f7478
Revises: e0664be3e4b6
Create Date: 2025-08-01 15:51:44.099057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514e677f7478'
down_revision: Union[str, Sequence[str], None] = 'e0664be3e4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('super_user', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_user_super_user'), 'user', ['super_user'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_super_user'), table_name='user')
    op.drop_column('user', 'super_user')
    # ### end Alembic commands ###
