"""Add client_roles to User model

Revision ID: 570d8dedf60e
Revises: 71598edfe977
Create Date: 2025-09-17 22:08:59.627704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570d8dedf60e'
down_revision: Union[str, Sequence[str], None] = '71598edfe977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_roles', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'client_roles')
    # ### end Alembic commands ###
