"""Add SurveyTemplate model and link questions

Revision ID: 57cf42b7f456
Revises: 35ea1f544186
Create Date: 2025-09-14 15:48:01.947329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57cf42b7f456'
down_revision: Union[str, Sequence[str], None] = '35ea1f544186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveytemplate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveytemplate_name'), 'surveytemplate', ['name'], unique=False)
    op.create_index(op.f('ix_surveytemplate_user_id'), 'surveytemplate', ['user_id'], unique=False)
    
    # MODIFICATION: Changed nullable=False to nullable=True to handle existing data
    op.add_column('surveyquestion', sa.Column('template_id', sa.Uuid(), nullable=True)) 
    
    op.drop_index(op.f('ix_surveyquestion_survey_type'), table_name='surveyquestion')
    op.create_index(op.f('ix_surveyquestion_template_id'), 'surveyquestion', ['template_id'], unique=False)
    op.create_foreign_key('fk_surveyquestion_template_id', 'surveyquestion', 'surveytemplate', ['template_id'], ['id'])
    op.drop_column('surveyquestion', 'survey_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveyquestion', sa.Column('survey_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'surveyquestion', type_='foreignkey')
    op.drop_index(op.f('ix_surveyquestion_template_id'), table_name='surveyquestion')
    op.create_index(op.f('ix_surveyquestion_survey_type'), 'surveyquestion', ['survey_type'], unique=False)
    op.alter_column('surveyquestion', 'question_type',
               existing_type=postgresql.ENUM('text', 'number', 'select', 'multi_select', 'range', 'boolean', name='questiontype'),
               nullable=False)
    op.drop_column('surveyquestion', 'template_id')
    op.drop_index(op.f('ix_surveytemplate_user_id'), table_name='surveytemplate')
    op.drop_index(op.f('ix_surveytemplate_name'), table_name='surveytemplate')
    op.drop_table('surveytemplate')
    # ### end Alembic commands ###
