"""Add welcome pack fields to user and client

Revision ID: 658563a47839
Revises: 570d8dedf60e
Create Date: 2025-09-18 08:28:07.990149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '658563a47839'
down_revision: Union[str, Sequence[str], None] = '570d8dedf60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('client_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('client', sa.Column('welcome_pack_override', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('welcome_pack_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('welcome_packs_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'welcome_packs_config')
    op.drop_column('user', 'welcome_pack_message')
    op.drop_column('client', 'welcome_pack_override')
    op.drop_column('client', 'client_role')
    # ### end Alembic commands ###
