"""Add updated_at column to campaignbriefing table

Revision ID: 6fced02bbabe
Revises: 514e677f7478
Create Date: 2025-08-04 19:43:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '6fced02bbabe'
down_revision = '514e677f7478' # Make sure this matches the previous revision ID
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaignbriefing', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaignbriefing', 'updated_at')
    # ### end Alembic commands ###