"""Set native_enum=False for QuestionType

Revision ID: 71598edfe977
Revises: ac6bf1de5ef5
Create Date: 2025-09-15 03:32:59.246617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71598edfe977'
down_revision: Union[str, Sequence[str], None] = 'ac6bf1de5ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_clientintakesurvey_template_id'), 'clientintakesurvey', ['template_id'], unique=False)
    op.alter_column('surveyquestion', 'template_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('surveyquestion', 'question_type',
               existing_type=postgresql.ENUM('text', 'number', 'select', 'multi_select', 'range', 'boolean', name='questiontype'),
               type_=sa.Enum('TEXT', 'NUMBER', 'SELECT', 'MULTI_SELECT', 'RANGE', 'BOOLEAN', name='questiontype', native_enum=False),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveyquestion', 'question_type',
               existing_type=sa.Enum('TEXT', 'NUMBER', 'SELECT', 'MULTI_SELECT', 'RANGE', 'BOOLEAN', name='questiontype', native_enum=False),
               type_=postgresql.ENUM('text', 'number', 'select', 'multi_select', 'range', 'boolean', name='questiontype'),
               nullable=False)
    op.alter_column('surveyquestion', 'template_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_clientintakesurvey_template_id'), table_name='clientintakesurvey')
    # ### end Alembic commands ###
