"""add_portal_link_table

Revision ID: 8027110b2edf
Revises: 447f04b9000c
Create Date: 2025-08-16 00:41:32.293710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8027110b2edf'
down_revision: Union[str, Sequence[str], None] = '447f04b9000c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portallink',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaignbriefing.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portallink_campaign_id'), 'portallink', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_portallink_client_id'), 'portallink', ['client_id'], unique=False)
    op.create_index(op.f('ix_portallink_is_active'), 'portallink', ['is_active'], unique=False)
    op.create_index(op.f('ix_portallink_user_id'), 'portallink', ['user_id'], unique=False)
    op.alter_column('portalcomment', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portalcomment', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_portallink_user_id'), table_name='portallink')
    op.drop_index(op.f('ix_portallink_is_active'), table_name='portallink')
    op.drop_index(op.f('ix_portallink_client_id'), table_name='portallink')
    op.drop_index(op.f('ix_portallink_campaign_id'), table_name='portallink')
    op.drop_table('portallink')
    # ### end Alembic commands ###
