"""add survey and portal models

Revision ID: 8d8a21dcd8ba
Revises: 015cefa1a6b3
Create Date: 2025-08-13 02:58:49.099335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d8a21dcd8ba'
down_revision: Union[str, Sequence[str], None] = '015cefa1a6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('secure_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_client_id'), 'portal', ['client_id'], unique=False)
    op.create_index(op.f('ix_portal_secure_token'), 'portal', ['secure_token'], unique=True)
    op.create_index(op.f('ix_portal_user_id'), 'portal', ['user_id'], unique=False)
    
    op.create_table('portalcomment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('comment_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portalcomment_client_id'), 'portalcomment', ['client_id'], unique=False)
    op.create_index(op.f('ix_portalcomment_resource_id'), 'portalcomment', ['resource_id'], unique=False)

    op.create_table('portalfeedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portalfeedback_client_id'), 'portalfeedback', ['client_id'], unique=False)
    op.create_index(op.f('ix_portalfeedback_resource_id'), 'portalfeedback', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portalfeedback_resource_id'), table_name='portalfeedback')
    op.drop_index(op.f('ix_portalfeedback_client_id'), table_name='portalfeedback')
    op.drop_table('portalfeedback')
    op.drop_index(op.f('ix_portalcomment_resource_id'), table_name='portalcomment')
    op.drop_index(op.f('ix_portalcomment_client_id'), table_name='portalcomment')
    op.drop_table('portalcomment')
    op.drop_index(op.f('ix_portal_user_id'), table_name='portal')
    op.drop_index(op.f('ix_portal_secure_token'), table_name='portal')
    op.drop_index(op.f('ix_portal_client_id'), table_name='portal')
    op.drop_table('portal')
    # ### end Alembic commands ###