"""refactor ClientIntakeSurvey to use template_id

Revision ID: ac6bf1de5ef5
Revises: 57cf42b7f456
Create Date: 2025-09-14 23:49:48.321115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ac6bf1de5ef5'
down_revision: Union[str, Sequence[str], None] = '57cf42b7f456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientintakesurvey', sa.Column('template_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(
        "fk_clientintakesurvey_template_id",
        'clientintakesurvey', 'surveytemplate',
        ['template_id'], ['id']
    )
    op.drop_index('ix_clientintakesurvey_survey_type', table_name='clientintakesurvey')
    op.drop_column('clientintakesurvey', 'survey_version')
    op.drop_column('clientintakesurvey', 'preferences_extracted')
    op.drop_column('clientintakesurvey', 'tags_generated')
    op.drop_column('clientintakesurvey', 'survey_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientintakesurvey', sa.Column('survey_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('clientintakesurvey', sa.Column('tags_generated', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('clientintakesurvey', sa.Column('preferences_extracted', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('clientintakesurvey', sa.Column('survey_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_clientintakesurvey_survey_type', 'clientintakesurvey', ['survey_type'], unique=False)
    op.drop_constraint("fk_clientintakesurvey_template_id", 'clientintakesurvey', type_='foreignkey')
    op.drop_column('clientintakesurvey', 'template_id')
    # ### end Alembic commands ###
