"""Add edited_draft column to campaignbriefing table

Revision ID: add_edited_draft_to_campaignbriefing
Revises: 6fced02bbabe
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'add_edited_draft_column'
down_revision = '6fced02bbabe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaignbriefing', sa.Column('edited_draft', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaignbriefing', 'edited_draft')
    # ### end Alembic commands ### 