"""Add negativepreference table

Revision ID: add_negativepreference_table
Revises: 2ce7c9665fe8
Create Date: 2025-07-27 01:07:38.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_negativepreference_table'
down_revision: Union[str, None] = '2ce7c9665fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negativepreference',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('client_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dismissed_embedding', sa.JSON(), nullable=False),
    sa.Column('source_campaign_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negativepreference_client_id'), 'negativepreference', ['client_id'], unique=False)
    op.create_index(op.f('ix_negativepreference_source_campaign_id'), 'negativepreference', ['source_campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negativepreference_source_campaign_id'), table_name='negativepreference')
    op.drop_index(op.f('ix_negativepreference_client_id'), table_name='negativepreference')
    op.drop_table('negativepreference')
    # ### end Alembic commands ###