"""Add source column to campaignbriefing

Revision ID: cbe7cd5783fa
Revises: add_edited_draft_column
Create Date: 2025-08-09 14:01:25.367998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbe7cd5783fa'
down_revision: Union[str, Sequence[str], None] = 'add_edited_draft_column'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaignbriefing', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_campaignbriefing_source'), 'campaignbriefing', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaignbriefing_source'), table_name='campaignbriefing')
    op.drop_column('campaignbriefing', 'source')
    # ### end Alembic commands ###
