"""Add GlobalMlsEvent table

Revision ID: e0664be3e4b6
Revises: merge_heads_migration
Create Date: 2025-07-27 09:34:14.417684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0664be3e4b6'
down_revision: Union[str, Sequence[str], None] = 'merge_heads_migration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globalmlsevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('listing_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'listing_key', name='ux_source_id_listing_key')
    )
    op.create_index(op.f('ix_globalmlsevent_created_at'), 'globalmlsevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_globalmlsevent_event_timestamp'), 'globalmlsevent', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_globalmlsevent_id'), 'globalmlsevent', ['id'], unique=False)
    op.create_index(op.f('ix_globalmlsevent_listing_key'), 'globalmlsevent', ['listing_key'], unique=False)
    op.create_index(op.f('ix_globalmlsevent_source_id'), 'globalmlsevent', ['source_id'], unique=False)
    op.create_index(op.f('ix_marketevent_created_at'), 'marketevent', ['created_at'], unique=False)
    op.create_index(op.f('ix_marketevent_entity_id'), 'marketevent', ['entity_id'], unique=False)
    op.create_index(op.f('ix_marketevent_event_type'), 'marketevent', ['event_type'], unique=False)
    op.create_index('ix_marketevent_user_created', 'marketevent', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_marketevent_user_type', 'marketevent', ['user_id', 'event_type'], unique=False)
    op.alter_column('negativepreference', 'dismissed_embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('negativepreference', 'dismissed_embedding',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index('ix_marketevent_user_type', table_name='marketevent')
    op.drop_index('ix_marketevent_user_created', table_name='marketevent')
    op.drop_index(op.f('ix_marketevent_event_type'), table_name='marketevent')
    op.drop_index(op.f('ix_marketevent_entity_id'), table_name='marketevent')
    op.drop_index(op.f('ix_marketevent_created_at'), table_name='marketevent')
    op.drop_index(op.f('ix_globalmlsevent_source_id'), table_name='globalmlsevent')
    op.drop_index(op.f('ix_globalmlsevent_listing_key'), table_name='globalmlsevent')
    op.drop_index(op.f('ix_globalmlsevent_id'), table_name='globalmlsevent')
    op.drop_index(op.f('ix_globalmlsevent_event_timestamp'), table_name='globalmlsevent')
    op.drop_index(op.f('ix_globalmlsevent_created_at'), table_name='globalmlsevent')
    op.drop_table('globalmlsevent')
    # ### end Alembic commands ###
