# ---
# File Path: backend/data/models/campaign.py
# Purpose: Defines the data models for the "Campaign-in-a-Box" feature.
# ---
from pydantic import BaseModel, Field, HttpUrl # <-- NEW: Import HttpUrl
from typing import List, Dict, Any, Literal, Optional
from uuid import UUID, uuid4
from datetime import datetime, timezone

class MatchedClient(BaseModel):
    """Represents a single client within a campaign's target audience."""
    client_id: UUID
    client_name: str
    match_score: int
    match_reason: str

class CampaignBriefing(BaseModel):
    """
    Represents a complete "Campaign-in-a-Box" generated by the Nudge Engine.
    """
    id: UUID = Field(default_factory=uuid4)
    user_id: UUID
    campaign_type: Literal[
        "price_drop", "new_listing", "market_trend", 
        "birthday_greeting", "holiday_greeting", "quarterly_check_in", "intel_suggestion"
    ] = "price_drop"
    headline: str
    key_intel: Dict[str, Any]
    
    # NEW: A dedicated field for the listing URL for the Realtor to verify.
    listing_url: Optional[HttpUrl] = Field(None, description="A direct link to the MLS listing for verification.")

    original_draft: str
    edited_draft: Optional[str] = None
    matched_audience: List[MatchedClient]
    sent_messages: Optional[Dict[UUID, Dict[str, Any]]] = None
    triggering_event_id: UUID
    status: Literal["new", "launched", "dismissed"] = "new"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Config:
        from_attributes = True