# ---
# File Path: backend/data/models/nudge.py
# Purpose: Defines the data model for an AI-generated Nudge.
# ---
from pydantic import BaseModel, Field
from typing import Dict, Any, Literal
from uuid import UUID, uuid4
from datetime import datetime, timezone

class Nudge(BaseModel):
    """Represents an actionable insight generated by the AI for the user."""
    id: UUID = Field(default_factory=uuid4)
    user_id: UUID
    client_id: UUID

    insight_headline: str
    drafted_message: str
    
    # NEW: A human-readable string explaining why this match was made.
    # This helps the Realtor trust the system's recommendations.
    match_reason: str = Field(description="The reason a match was identified.")

    triggering_event_id: UUID
    status: Literal["new", "sent", "dismissed"] = "new"
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Config:
        from_attributes = True